# Generated by Django 5.1.2 on 2025-02-26 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='user_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
