# Generated by Django 5.1.2 on 2025-02-26 13:39

import django.db.models.deletion
import vacancyapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0002_userstatus_user_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_position', models.CharField(choices=[('Assistant', 'Assistant'), ('Senior Assistant', 'Senior Assistant'), ('Officer', 'Officer')], default='Assistant', max_length=50)),
                ('vacancy_level', models.CharField(choices=[(4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default='Level 4', max_length=10)),
                ('vacancy_group', models.CharField(choices=[('Administration', 'Administration'), ('IT', 'IT')], default='Administration', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('upload_citizenship', models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancyapp.vacancyinfo')),
            ],
        ),
    ]
