# Generated by Django 5.1.2 on 2025-02-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0003_vacancyinfo_applicantinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user_created_at',
            field=models.DateField(blank=True),
        ),
    ]
