# Generated by Django 5.1.2 on 2025-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0005_alter_userstatus_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantinfo',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantinfo',
            name='issued_district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
