# Generated by Django 5.1.2 on 2025-02-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0006_applicantinfo_dob_applicantinfo_issued_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantinfo',
            name='applied_to',
        ),
        migrations.AddField(
            model_name='vacancyinfo',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacancyapp.applicantinfo'),
            preserve_default=False,
        ),
    ]
