# Generated by Django 5.1.6 on 2025-02-28 10:47

import vacancyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0010_educationinfo_user_vacancyinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfo',
            name='upload_character',
            field=models.FileField(default=1, help_text='(pdf of jpg)', upload_to=vacancyapp.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='upload_license',
            field=models.FileField(blank=True, help_text='(pdf of jpg)', upload_to=vacancyapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='upload_other',
            field=models.FileField(blank=True, help_text='(pdf of jpg)', upload_to=vacancyapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='upload_other1',
            field=models.FileField(blank=True, help_text='(pdf of jpg)', upload_to=vacancyapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='upload_transcript1',
            field=models.FileField(default=1, help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='upload_transcript2',
            field=models.FileField(default=1, help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantinfo',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
