# Generated by Django 5.1.6 on 2025-02-28 10:57

import django.db.models.deletion
import vacancyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0011_educationinfo_upload_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancyinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='vacancyinfo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantinfo',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantinfo',
            name='upload_citizenship',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_infos', to='vacancyapp.applicantinfo'),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='grade_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='passed_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_character',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_license',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_other',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_other1',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_transcript1',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_transcript2',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.user_directory_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_infos', to='vacancyapp.applicantinfo'),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_level',
            field=models.IntegerField(choices=[(4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=4),
        ),
    ]
