# Generated by Django 5.1.6 on 2025-02-28 12:25

import vacancyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0012_remove_educationinfo_user_remove_vacancyinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_character',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_license',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_other',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_other1',
            field=models.FileField(blank=True, help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_transcript1',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='upload_transcript2',
            field=models.FileField(help_text='(pdf or jpg)', upload_to=vacancyapp.models.education_document_path, validators=[vacancyapp.models.validate_file_extension]),
        ),
    ]
