# Generated by Django 5.1.6 on 2025-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0013_alter_educationinfo_upload_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyinfo',
            name='vacancy_applied_date',
            field=models.DateField(default='2025-03-02'),
        ),
    ]
