# Generated by Django 5.1.6 on 2025-03-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0014_vacancyinfo_vacancy_applied_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyinfo',
            name='vacancy_applied_date',
        ),
    ]
