# Generated by Django 5.1.2 on 2025-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0015_remove_vacancyinfo_vacancy_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_group',
            field=models.CharField(default='Administration', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_level',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_position',
            field=models.CharField(default='Assistant', max_length=50),
        ),
    ]
