# Generated by Django 5.1.2 on 2025-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0016_alter_vacancyinfo_vacancy_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_group',
            field=models.CharField(choices=[('Administration', 'Administration'), ('IT', 'IT')], default='Administration', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_level',
            field=models.IntegerField(choices=[(4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6')], default=4),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_position',
            field=models.CharField(choices=[('Assistant', 'Assistant'), ('Senior Assistant', 'Senior Assistant'), ('Officer', 'Officer')], default='Assistant', max_length=50),
        ),
    ]
