# Generated by Django 5.1.2 on 2025-03-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0018_alter_vacancyinfo_vacancy_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_group',
            field=models.CharField(choices=[('Administration', 'Administration'), ('IT', 'IT')], default='Administration', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_position',
            field=models.CharField(choices=[('Assistant', 'Assistant(Level 4)'), ('Senior Assistant()', 'Senior Assistant(Level 5)'), ('Officer', 'Officer(Level 6)')], default='Assistant', max_length=50),
        ),
    ]
