# Generated by Django 5.1.2 on 2025-03-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0019_alter_vacancyinfo_vacancy_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_level',
            field=models.CharField(choices=[('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6')], default='Level 4', max_length=8),
        ),
    ]
