# Generated by Django 5.1.2 on 2025-03-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0020_alter_vacancyinfo_vacancy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_position',
            field=models.CharField(choices=[('Assistant(Level 4)', 'Assistant(Level 4)'), ('Senior Assistant(Level 5)', 'Senior Assistant(Level 5)'), ('Officer(Level 6)', 'Officer(Level 6)')], default='Assistant', max_length=50),
        ),
    ]
