# Generated by Django 5.1.2 on 2025-03-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0021_alter_vacancyinfo_vacancy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyinfo',
            name='vacancy_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
