# Generated by Django 5.1.2 on 2025-03-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0022_vacancyinfo_vacancy_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyinfo',
            name='vacancy_level',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
