# Generated by Django 5.1.6 on 2025-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0023_alter_vacancyinfo_vacancy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyinfo',
            name='vacancy_status',
            field=models.CharField(default='Pending', max_length=9),
        ),
    ]
