# Generated by Django 5.1.6 on 2025-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0024_vacancyinfo_vacancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyinfo',
            name='is_payment_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancyinfo',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
