# Generated by Django 5.1.6 on 2025-03-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0025_vacancyinfo_is_payment_made_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancyinfo',
            unique_together={('applicant', 'vacancy_position')},
        ),
    ]
