# Generated by Django 5.1.2 on 2025-03-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0026_alter_vacancyinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancyinfo',
            unique_together={('applicant', 'vacancy_position', 'vacancy_group')},
        ),
    ]
